### ISSUE TITLE
Use consumet.ts instead of the consumet API

### ISSUE THREAD

**Issue by zisra** [movie-web/providers#4]
[Consumet](https://github.com/consumet/api.consumet.org) is an API wrapped around [consumet.ts](https://github.com/consumet/consumet.ts). The API only manages things like caching and ratelimiting. 

By switching to consumet.ts we will not have to be dependent to an API. Instead, we would implement the [FlixHQ scraper code](https://github.com/consumet/consumet.ts/blob/master/src/providers/movies/flixhq.ts) just like any other provider. 

Also, we should add the other providers in the consumet.ts library to implement anime and a greater variety of providers. The consumet.ts library also handles embeds (they call it extractors) for video hosting services like filemoon, vidcloud, and streamtape. This would mostly be copy-and-pasting code but we need to swictch to cheerio first for that (#3 )

**Comment by mrjvs** [comment]
sounds good, but not in scope for version 4 as the feature list has been defined beforehand.
also we will need to investigate if its even feasible for a browser to run the consumet scrapers

**Comment by mrjvs** [comment]
closing this issue, as we no longer use consumet directly in any way.
We only reimplement their providers manually.
